pub mod add_authorised_principal;
pub mod insert_category;
pub mod insert_collection;
pub mod remove_collection;
pub mod remove_category;
pub mod set_category_visibility;
pub mod update_collection;
pub mod insert_fake_collection;
pub mod toggle_promoted;
