default:
  image: dckreg.bity.com/bity/dev/runners_images/dfinity-canisters:0.31.0
  interruptible: true
  before_script:
    - dfx --version
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - api_failure
      - runner_unsupported
      - unknown_failure

cache:
  - key: "dfx-$CI_COMMIT_REF_SLUG"
    paths:
      - .dfx

stages:
  - preparation
  - lint
  - build
  - test
  - integration_testing
  - deploy

include:
  # Templates:
  - local: scripts/ci-cd/.node_template.yml
  - local: scripts/ci-cd/.rust_template.yml
  # Frontend linters:
  - local: scripts/ci-cd/.frontend_linter.yml
    inputs:
      src-folder: ogy_dashboard
  - local: scripts/ci-cd/.frontend_linter.yml
    inputs:
      src-folder: origyn_landing_page

################################################################################
# Unit Tests
################################################################################
  - local: scripts/ci-cd/.canister_unit_test_coverage.yml
    inputs:
      src-folder: ogy_token_swap
  - local: scripts/ci-cd/.canister_unit_test_coverage.yml
    inputs:
      src-folder: sns_rewards
  - local: scripts/ci-cd/.canister_unit_test_coverage.yml
    inputs:
      src-folder: collection_index
  - local: scripts/ci-cd/.canister_unit_test_coverage.yml
    inputs:
      src-folder: sns_neuron_controller
  - local: scripts/ci-cd/.canister_unit_test_coverage.yml
    inputs:
      src-folder: dex_interaction
  # - local: scripts/ci-cd/.canister_unit_test_coverage.yml
  #   inputs:
  #     src-folder: token_metrics
  - local: scripts/ci-cd/.canister_unit_test_coverage.yml
    inputs:
      src-folder: canister_jobs

################################################################################
# Canister Builds
################################################################################
  - local: scripts/ci-cd/.canister_builds.yml
    inputs:
      src-folder: ogy_token_swap
  - local: scripts/ci-cd/.canister_builds.yml
    inputs:
      src-folder: sns_rewards
  - local: scripts/ci-cd/.canister_builds.yml
    inputs:
      src-folder: collection_index
  - local: scripts/ci-cd/.canister_builds.yml
    inputs:
      src-folder: sns_neuron_controller
  - local: scripts/ci-cd/.canister_builds.yml
    inputs:
      src-folder: dex_interaction
  # - local: scripts/ci-cd/.canister_builds.yml
  #   inputs:
  #     src-folder: token_metrics
  - local: scripts/ci-cd/.canister_builds.yml
    inputs:
      src-folder: canister_jobs

  # Canister generate declaration
  # - local: scripts/ci-cd/.generate_declaration.yml
  #   inputs:
  #     src-folder: ogy_token_swap
  # - local: scripts/ci-cd/.generate_declaration.yml
  #   inputs:
  #     src-folder: sns_rewards
  # - local: scripts/ci-cd/.generate_declaration.yml
  #   inputs:
  #     src-folder: sns_neuron_controller
  # - local: scripts/ci-cd/.generate_declaration.yml
  #   inputs:
  #     src-folder: token_metrics
  # - local: scripts/ci-cd/.generate_declaration.yml
  #   inputs:
  #     src-folder: canister_jobs

################################################################################
# Frontend Builds preparation
################################################################################
  - local: scripts/ci-cd/.frontend_builds.yml
    inputs:
      src-folder: ogy_dashboard
  - local: scripts/ci-cd/.frontend_builds.yml
    inputs:
      src-folder: origyn_landing_page

################################################################################
# Integration Tests
################################################################################
  - local: scripts/ci-cd/.integration_tests.yml

################################################################################
# Backend deployments
################################################################################
  - local: scripts/ci-cd/.canister_deploys.yml
    inputs:
      src-folder: ogy_token_swap
  - local: scripts/ci-cd/.canister_deploys.yml
    inputs:
      src-folder: sns_rewards
  - local: scripts/ci-cd/.canister_deploys.yml
    inputs:
      src-folder: sns_neuron_controller
  - local: scripts/ci-cd/.canister_deploys.yml
    inputs:
      src-folder: dex_interaction
  # - local: scripts/ci-cd/.canister_deploys.yml
  #   inputs:
  #     src-folder: token_metrics
  - local: scripts/ci-cd/.canister_deploys.yml
    inputs:
      src-folder: canister_jobs
  - local: scripts/ci-cd/.canister_deploys.yml
    inputs:
      src-folder: collection_index
  # Deployments
  - local: scripts/ci-cd/.dfx_templates.yml

################################################################################
# Cache preparation
################################################################################
node cache:
  stage: preparation
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - "./frontend/{**,**/**,**/**/**}/*.{js,json,jsx,md,mdx,css,html,svg}"
  extends: .node template
  script:
    - npm pkg get name description author license workspaces engines
    - node --version
    - npm --version

################################################################################
# Linters
################################################################################

# See includes above for frontends lint

rust lint:
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - "Cargo.{lock,toml}"
        - "backend/{**,**/**,**/**/**}/*.{rs,toml,lock}"
    - if: $CI_OPEN_MERGE_REQUESTS
      when: never
      changes:
        - "Cargo.{lock,toml}"
        - "backend/{**,**/**,**/**/**}/*.{rs,toml,lock}"
    - if: $CI_COMMIT_REF_NAME == "develop"
      changes:
        - "Cargo.{lock,toml}"
        - "backend/{**,**/**,**/**/**}/*.{rs,toml,lock}"
  extends: .rust template
  script:
    - cargo clippy

#######
# DEPLOYMENTS FRONTEND
#######

ogy dashboard staging:
  stage: deploy
  resource_group: frontend staging deployment
  variables:
    CANISTER_NAME: "ogy_dashboard"
  rules:
    - if: $CI_COMMIT_REF_NAME == "develop" && $CI_PIPELINE_SOURCE != "merge_request_event"
      changes:
        - "frontend/ogy_dashboard/*.{js,json}"
        - "frontend/ogy_dashboard/{**,**/**,**/**/**}/*.{js,jsx,ts,tsx,md,mdx,css,html,svg}"
      needs: ["ogy_dashboard staging build"]
      variables:
        TARGET_NETWORK: staging
        PEM_FILE: "${PEM_FILE_STAGING}"
  before_script:
    - !reference [.import dfx identity, before_script]
  script:
    - !reference [.asset canister staging deploy, script]
  environment:
    name: ogy dashboard
    deployment_tier: staging
    url: https://7ekbt-siaaa-aaaag-ak64a-cai.icp0.io/
    action: start

ogy dashboard preprod:
  stage: deploy
  resource_group: frontend staging deployment
  variables:
    CANISTER_NAME: "ogy_dashboard"
  rules:
    - if: $CI_COMMIT_REF_NAME == "develop" && $CI_PIPELINE_SOURCE != "merge_request_event"
      changes:
        - "frontend/ogy_dashboard/*.{js,json}"
        - "frontend/ogy_dashboard/{**,**/**,**/**/**}/*.{js,jsx,ts,tsx,md,mdx,css,html,svg}"
      needs: ["ogy_dashboard preprod build"]
      variables:
        TARGET_NETWORK: preprod
        PEM_FILE: "${PEM_FILE_STAGING}"
  before_script:
    - !reference [.import dfx identity, before_script]
  script:
    - !reference [.asset canister preprod deploy, script]
  environment:
    name: ogy dashboard
    deployment_tier: staging
    url: https://m7nki-xaaaa-aaaan-qmlwa-cai.icp0.io/
    action: start

ogy dashboard production:
  stage: deploy
  resource_group: frontend production deployment
  variables:
    CANISTER_NAME: "ogy_dashboard"
  rules:
    - if: $CI_COMMIT_TAG =~ '/^ogy_dashboard-v\d+\.\d+\.\d+$/'
      changes:
        - "frontend/ogy_dashboard/*.{js,json}"
        - "frontend/ogy_dashboard/{**,**/**,**/**/**}/*.{js,jsx,ts,tsx,md,mdx,css,html,svg}"
      needs: ["ogy_dashboard production build"]
      variables:
        TARGET_NETWORK: ic
        PEM_FILE: "${PEM_FILE_PRODUCTION}"
  before_script:
    - !reference [.import dfx identity, before_script]
  script:
    - !reference [.asset canister production deploy, script]
  environment:
    name: ogy dashboard
    deployment_tier: production
    url: https://jbj2y-2qaaa-aaaal-ajc5q-cai.icp0.io/
    action: start

ogy landing page staging:
  stage: deploy
  resource_group: frontend staging deployment
  variables:
    CANISTER_NAME: "origyn_landing_page"
  rules:
    - if: $CI_COMMIT_REF_NAME == "develop" && $CI_PIPELINE_SOURCE != "merge_request_event"
      changes:
        - "frontend/origyn_landing_page/*.{js,json}"
        - "frontend/origyn_landing_page/{**,**/**,**/**/**}/*.{js,jsx,ts,tsx,md,mdx,css,html,svg}"
      needs: ["origyn_landing_page staging build"]
      variables:
        TARGET_NETWORK: staging
        PEM_FILE: "${PEM_FILE_STAGING}"
  before_script:
    - !reference [.import dfx identity, before_script]
  script:
    - !reference [.asset canister staging deploy, script]
  environment:
    name: ogy dashboard
    deployment_tier: staging
    url: https://ujkle-wiaaa-aaaap-qhxsa-cai.icp0.io/
    action: start

ogy landing page production:
  stage: deploy
  resource_group: frontend production deployment
  variables:
    CANISTER_NAME: "origyn_landing_page"
  rules:
    - if: $CI_COMMIT_TAG =~ '/^origyn_landing_page-v\d+\.\d+\.\d+$/'
      changes:
        - "frontend/origyn_landing_page/*.{js,json}"
        - "frontend/origyn_landing_page/{**,**/**,**/**/**}/*.{js,jsx,ts,tsx,md,mdx,css,html,svg}"
      needs: ["origyn_landing_page production build"]
      variables:
        TARGET_NETWORK: ic
        PEM_FILE: "${PEM_FILE_PRODUCTION}"
  before_script:
    - !reference [.import dfx identity, before_script]
  script:
    - !reference [.asset canister production deploy, script]
  environment:
    name: origyn landing page
    deployment_tier: production
    url: https://origyn.com
    action: start
