[package]
name = "integration_tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
ic-ledger-types = { workspace = true }
icrc-ledger-types = { workspace = true }
lazy_static = { workspace = true }
serde_bytes = { workspace = true }
ledger_utils = { path = "../libraries/ledger_utils" }
ogy_legacy_ledger_canister_c2c_client = { path = '../external_canisters/ogy_legacy_ledger/c2c_client' }

pocket-ic = { workspace = true }
rand = "0.8.5"
slog = "2.7.0"
serde = { workspace = true }
types = { path = "../libraries/types" }
utils = { path = "../libraries/utils" }
sha2 = "0.10.8"
hex = "0.4"
bity-ic-canister-time = { workspace = true }
bity-ic-types = { workspace = true }
bity-ic-ledger-utils = { workspace = true }

# SNS
sns_governance_canister = { path = '../external_canisters/sns_governance/api' }
sns_governance_canister_c2c_client = { path = '../external_canisters/sns_governance/c2c_client' }
sns_root_canister = { path = '../external_canisters/sns_root/api' }
sns_ledger_canister = { path = '../external_canisters/sns_ledger/api' }
sns_swap_canister = { path = '../external_canisters/sns_swap/api' }
sns_index_canister = { path = '../external_canisters/sns_index/api' }

nns_governance_canister = { path = '../external_canisters/nns_governance/api' }

# DFINITY crates
# ic-nns-test-utils = { git = "https://github.com/dfinity/ic.git", branch = "master", package = "ic-nns-test-utils" }
ic-nns-governance-api = { git = "https://github.com/dfinity/ic.git", branch = "master", package = "ic-nns-governance-api" }
ic-nns-common = { git = "https://github.com/dfinity/ic.git", branch = "master", package = "ic-nns-common" }
ic-management-canister-types = "0.5"


# Canisters API
dex_interaction_api = { path = "../canisters/dex_interaction/api" }
sns_neuron_controller_api_canister = { path = "../canisters/sns_neuron_controller/api" }
sns_rewards_api_canister = { path = "../canisters/sns_rewards/api" }
ogy_token_swap_api = { path = "../canisters/ogy_token_swap/api" }
collection_index_api = { path = "../canisters/collection_index/api" }
canister_jobs_api = { path = "../canisters/canister_jobs/api" }
origyn_nft_reference = { path = '../external_canisters/origyn_nft_reference/api' }
ogy_legacy_ledger_canister = { path = '../external_canisters/ogy_legacy_ledger/api' }
icrc_ledger_canister = { path = "../external_canisters/icrc_ledger/api" }