# dfx and quill commands templates

.import dfx identity:
  before_script:
    - echo "Loading identity for network" $TARGET_NETWORK
    - dfx --version
    - dfx identity import --storage-mode plaintext gitlab-ci-ogy $PEM_FILE
    - dfx identity use gitlab-ci-ogy
    - dfx identity whoami
    - if [[ $(date -R) == "Fri"* ]]; then echo "It appear you are deploying on a Friday....."; fi
    - dfx identity get-principal

.asset canister staging deploy:
  script:
    - dfx deploy --network $TARGET_NETWORK --no-wallet --mode reinstall -y ${CANISTER_NAME}
    # - . scripts/parse_proposal_details.sh
    # - . scripts/prepare_sns_canister_ids.sh staging
    # - dfx deploy --network $TARGET_NETWORK --no-wallet --mode reinstall --by-proposal -y ${CANISTER_NAME}
    # - >
    #   quill sns --canister-ids-file sns/scripts/sns_canister_ids.json make-upgrade-canister-proposal $SNS_PROPOSER_NEURON_ID_STAGING
    #   --pem-file $PEM_FILE
    #   --target-canister-id $(cat canister_ids.json | jq -r .${CANISTER_NAME}.staging)
    #   --wasm-path /builds/origyn/ogy_token_swap/.dfx/local/canisters/${CANISTER_NAME}/${CANISTER_NAME}.wasm.gz
    #   --title "Upgrade ${CANISTER_NAME} to ${CI_COMMIT_SHORT_SHA}"
    #   --url ${DETAILS_URL} --summary-path proposal.md | quill send $TEST_QUILL --yes -

.asset canister preprod deploy:
  script:
    - dfx deploy --network $TARGET_NETWORK --no-wallet --mode reinstall -y ${CANISTER_NAME}

.asset canister production deploy:
  script:
    - dfx deploy --network $TARGET_NETWORK --no-wallet ${CANISTER_NAME}
    # - . scripts/parse_proposal_details.sh
    # - . scripts/prepare_sns_canister_ids.sh ic
    # - dfx deploy --network $TARGET_NETWORK --no-wallet --mode reinstall --by-proposal -y ${CANISTER_NAME}
    # - >
    #   quill sns --canister-ids-file sns/scripts/sns_canister_ids.json make-upgrade-canister-proposal $SNS_PROPOSER_NEURON_ID_PRODUCTION
    #   --pem-file $PEM_FILE
    #   --target-canister-id $(cat canister_ids.json | jq -r .${CANISTER_NAME}.ic)
    #   --wasm-path /builds/origyn/ogy_token_swap/.dfx/local/canisters/${CANISTER_NAME}/${CANISTER_NAME}.wasm.gz
    #   --title "Upgrade ${CANISTER_NAME} to ${CI_COMMIT_TAG}"
    #   --url ${DETAILS_URL} --summary-path proposal.md | quill send $TEST_QUILL --yes -
