spec:
  inputs:
    src-folder:
      description: Generate declatations for the canister
      options: ["ogy_token_swap", "sns_rewards", "super_stats_v3", "token_metrics"]
---
# Frontend builds


$[[ inputs.src-folder ]] generate test declaration:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      needs:
        - "${{ inputs.directory }} test build"
  script:
    - dfx generate ${{ inputs.directory }}
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_SHORT_SHA}-TEST-declarations"
    paths:
      - backend/**/declarations
    expire_in: 1 day

$[[ inputs.src-folder ]] generate declaration:
  stage: build
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
      when: never
    - if: $CI_COMMIT_REF_NAME == "develop" || $CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME =~ '/^(?:ogy_dashboard)-v\d+\.\d+\.\d+$/'
      needs:
        - "${{ inputs.directory }} canister build"
  script:
    - dfx generate ${{ inputs.directory }}
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_SHORT_SHA}-declarations"
    paths:
      - backend/**/api
    expire_in: 1 day

