# NodeJS & NextJS job template

.node template:
  image: node:18
  cache:
  - key: "node-$CI_COMMIT_REF_SLUG"
    paths:
      - .npm/
      - node_modules/
      - frontend/**/.npm/
      - frontend/**/node_modules/
  before_script:
    - npm ci --cache .npm --prefer-offline
