# Rust / Cargo (for wasm builds) template

.rust template:
  tags:
    - docker
    # - big
  image: rust:slim-bookworm@sha256:de22cea71b620c7fdc61e8c1bf3f048d0ffbafe062ca9d7b32aed6a7d59109a4
  cache:
  - key: "rust-$CI_COMMIT_REF_SLUG"
    paths:
      - .cargo
      - backend/canisters/ogy_token_swap/target
      - backend/canisters/sns_rewards/target
      - backend/canisters/super_stats_v3/target
      - backend/canisters/token_metrics/target
  before_script:
    - apt update > /dev/null && apt install -y wget build-essential pkg-config libssl-dev > /dev/null
    - rustup component add clippy
    - rustup target add wasm32-unknown-unknown
    - mkdir -pv .cargo
    # - cargo install -q --root .cargo ic-wasm@0.5.0 candid-extractor cargo-tarpaulin@=0.29.2
    - cargo install -q --root .cargo ic-wasm@0.5.0 candid-extractor
    - export PATH="$PWD/.cargo/bin:$PATH"
