# Rust / Cargo (for wasm builds) template

.rust template:
  tags:
    - docker
    # - big
  image: registry.bochslerfinance.com/runners-images/dfinity-canisters/rust-dfinity-build-ci:latest@sha256:b59632605ba16b53d32d84d2934f46abfcdf56c59a1da45e0a1384bf7bb831db
  before_script:
    - cargo --version 
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - api_failure
      - runner_unsupported
      - unknown_failure
