[package]
name = "buyback_burn"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[features]
inttest = []

[dependencies]
candid = { workspace = true }
bity-ic-canister-logger = { workspace = true }
bity-ic-canister-state-macros = { workspace = true }
bity-ic-canister-tracing-macros = { workspace = true }
icpswap_client = { path = "../../../libraries/icpswap_client" }
bity-ic-canister-time = { workspace = true }
buyback_burn_api = { path = "../api" }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-cdk-timers = { workspace = true }
ic-ledger-types = { workspace = true }
ic-stable-structures = { workspace = true }
icrc_ledger_canister_c2c_client = { path = "../../../external_canisters/icrc_ledger/c2c_client" }
serde = { workspace = true }
serde_json = { workspace = true }
bity-ic-serializer = { workspace = true }
bity-ic-stable-memory = { workspace = true }
tracing = { workspace = true }
types = { path = "../../../libraries/types" }
utils = { path = "../../../libraries/utils" }
futures = { workspace = true }
icrc-ledger-types = { workspace = true }
async-trait = { workspace = true }
http_request = { path = '../../../libraries/http_request' }
enum_dispatch = { workspace = true }
anyhow = { workspace = true }
bity-ic-types = { workspace = true }