pub mod add_authorised_principal;
pub mod insert_category;
pub mod insert_collection;
pub mod insert_fake_collection;
pub mod remove_category;
pub mod remove_collection;
pub mod set_category_visibility;
pub mod toggle_promoted;
pub mod update_collection;

pub use add_authorised_principal::*;
pub use insert_category::*;
pub use insert_collection::*;
pub use insert_fake_collection::*;
pub use remove_category::*;
pub use remove_collection::*;
pub use set_category_visibility::*;
pub use toggle_promoted::*;
pub use update_collection::*;
