[package]
name = "sns_governance_canister"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = { workspace = true }
bity-ic-candid-gen = { workspace = true }
bity-ic-canister-time = { workspace = true }
hex = { workspace = true }
ic-stable-structures = { workspace = true }
serde = { workspace = true }
types = { path = "../../../libraries/types" }
tracing = { workspace = true }